# Generated by Django 4.0 on 2022-07-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[{'Up vote', 'up'}, {'Down vote', 'down'}], max_length=200),
        ),
    ]
